version: '3'
services:
  teamspeak:
    image: aheil/teamspeak3-server
    container_name: ts3_vladino_me
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      - TS3SERVER_LICENSE=accept
